### ISSUE TITLE
Creating "onzuivere" records

### ISSUE THREAD

**Issue by erikplekenpol** [wvanbergen/clieop#2]
When I want to create a record for a payment from the former Postbank, currentty ING-bank, I need to create a so-called "onzuiver" record. An "onzuiver" record is created by adding the city (and name) in which the payer lives to the record. How do I do this? According to the documentation from Interpay it should be something like this:

Woonplaatsbetalerrecord
Recordcode 9        0113
Variantcode X(1)   B
Woonplaatsbetaler X(35)
Filler X(10)

I can't see the 0113 recordtype in the record.rb. Can this be added easily?

**Comment by moiristo** [comment]
Fairly easy.. you need to extend the TYPE_DEFINITIONS in record.rb and then extend the to_clieop method in batch.rb to add this record. I suggest a transaction may contain a :payment_city key to accomplish this.

**Comment by moiristo** [comment]
Hi,

I added the records 0113 & 0173 to the type definitions. You can add an account city as follows:

``` ruby
{ :account_nr => 123456, :account_owner => 'you', :account_city => 'Enschede', :amount => 133.0, :description => "Testing a direct debt transaction\nCharging your bank account" }
```

Is this working for you? I've not released a new version yet, so you should use the master git branch. Note that all payment related classes have been moved to a different namespace as well (e.g. Clieop::File has become Clieop::Payment::File).

**Comment by erikplekenpol** [comment]
Thanks, I will be testing this coming Saturday. I'll let you know asap if it works.

**Comment by moiristo** [comment]
Can I close this issue?

**Comment by erikplekenpol** [comment]
Sorry for not letting you kniow earlier. We checked the generated CLIEOP File with the bank, and it seems to be in working order for Postbank/ING. 

Thanks for your work!
